# Generated by Django 4.1 on 2022-09-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("Indian Rupee", "INR"), ("Dollar", "$")],
                default="INR",
                max_length=24,
            ),
        ),
    ]
