# Generated by Django 4.1.1 on 2022-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("Indian Rupee", "INR"), ("Dollar", "D")],
                default="INR",
                max_length=24,
            ),
        ),
    ]
