# Generated by Django 4.1.1 on 2022-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("t", "Transgender")],
                max_length=12,
            ),
        ),
    ]
