# Generated by Django 4.1.1 on 2022-09-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(default="", max_length=500)),
            ],
        ),
    ]
