# Generated by Django 4.1.1 on 2022-09-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_wishlistmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistmodel",
            name="products",
            field=models.ManyToManyField(to="core.productmodel"),
        ),
    ]
