# Generated by Django 4.1.1 on 2022-09-30 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_wishlistmodel_created_on_wishlistmodel_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wishlistmodel",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="wishlistmodel",
            name="products",
            field=models.ManyToManyField(blank=True, to="core.productmodel"),
        ),
    ]
